# 1. Layers and Blocks

In [1]:
import tensorflow as tf

net = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dense(10),
])

X = tf.random.uniform((2, 20))
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.06222891, -0.17196688,  0.2036386 , -0.2251272 ,  0.22940761,
         0.34944227,  0.08656169, -0.12790237, -0.09025874,  0.2684117 ],
       [-0.09128021, -0.12361296,  0.11901814, -0.23772673,  0.06365148,
         0.31885412, -0.04279087,  0.08079015, -0.0642566 ,  0.11309112]],
      dtype=float32)>

## 1.1 Custom Block

In [2]:
class MLP(tf.keras.Model):
    # Declare a layer with model parameters. Here, we declare two fully
    # connected layers
    def __init__(self):
        # Call the constructor of the `MLP` parent class `Model` to perform
        # the necessary initialization. In this way, other function arguments
        # can also be specified during class instantiation, such as the model
        # parameters, `params` (to be described later)
        super().__init__()
        # Hidden layer
        self.hidden = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
        self.out = tf.keras.layers.Dense(units=10)  # Output layer

    # Define the forward propagation of the model, that is, how to return the
    # required model output based on the input `X`
    def call(self, X):
        return self.out(self.hidden((X)))

In [3]:
net = MLP()
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.13969803, -0.1913996 , -0.24217474, -0.2782334 , -0.16825482,
         0.09777202,  0.01107033,  0.09087402,  0.10981197, -0.00366692],
       [-0.18240345,  0.14917527, -0.35338515, -0.1436439 , -0.11380327,
         0.295904  ,  0.143857  , -0.20154278,  0.07379955,  0.02182088]],
      dtype=float32)>

## 1.2 The Sequential Block

In [4]:
class MySequential(tf.keras.Model):
    def __init__(self, *args):
        super().__init__()
        self.modules = []
        for block in args:
            # Here, `block` is an instance of a `tf.keras.layers.Layer`
            # subclass
            self.modules.append(block)

    def call(self, X):
        for module in self.modules:
            X = module(X)
        return X

In [5]:
net = MySequential(
    tf.keras.layers.Dense(units=256, activation=tf.nn.relu),
    tf.keras.layers.Dense(10))
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.15146804, -0.03545818, -0.1305592 ,  0.00319199, -0.08673549,
         0.17839594, -0.06062969, -0.22432752, -0.06102191, -0.26956275],
       [-0.16200311, -0.3693706 , -0.1258937 , -0.25277346,  0.14243928,
        -0.0049958 ,  0.11719096, -0.18466173, -0.1453983 , -0.16852704]],
      dtype=float32)>

## 1.3 Executing Code in The Forward Propagation Function

In [6]:
class FixedHiddenMLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()
        # Random weight parameters created with `tf.constant` are not updated
        # during training (i.e., constant parameters)
        self.rand_weight = tf.constant(tf.random.uniform((20, 20)))
        self.dense = tf.keras.layers.Dense(20, activation=tf.nn.relu)

    def call(self, inputs):
        X = self.flatten(inputs)
        # Use the created constant parameters, as well as the `relu` and
        # `matmul` functions
        X = tf.nn.relu(tf.matmul(X, self.rand_weight) + 1)
        # Reuse the fully-connected layer. This is equivalent to sharing
        # parameters with two fully-connected layers
        X = self.dense(X)
        # Control flow
        while tf.reduce_sum(tf.math.abs(X)) > 1:
            X /= 2
        return tf.reduce_sum(X)

In [7]:
net = FixedHiddenMLP()
net(X)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9486791>

In [8]:
# We can mix and match various ways of assembling blocks together. In the following example, we nest blocks in some creative ways.
class NestMLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.net = tf.keras.Sequential()
        self.net.add(tf.keras.layers.Dense(64, activation=tf.nn.relu))
        self.net.add(tf.keras.layers.Dense(32, activation=tf.nn.relu))
        self.dense = tf.keras.layers.Dense(16, activation=tf.nn.relu)

    def call(self, inputs):
        return self.dense(self.net(inputs))

chimera = tf.keras.Sequential()
chimera.add(NestMLP())
chimera.add(tf.keras.layers.Dense(20))
chimera.add(FixedHiddenMLP())
chimera(X)

<tf.Tensor: shape=(), dtype=float32, numpy=0.5655581>

# 2. Parameter Management

In [9]:
import tensorflow as tf

net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu),
    tf.keras.layers.Dense(1),
])

X = tf.random.uniform((2, 4))
net(X)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 0.11526399],
       [-0.04729105]], dtype=float32)>

## 2.1 Parameter Access

In [10]:
print(net.layers[2].weights)

[<tf.Variable 'dense_13/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[ 0.16626787],
       [ 0.2467295 ],
       [-0.230353  ],
       [-0.88905907]], dtype=float32)>, <tf.Variable 'dense_13/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


### 2.1.1 Targeted parameters

In [11]:
print(type(net.layers[2].weights[1]))
print(net.layers[2].weights[1])
print(tf.convert_to_tensor(net.layers[2].weights[1]))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'dense_13/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>
tf.Tensor([0.], shape=(1,), dtype=float32)


2.1.2 All Parameters at Once

In [12]:
print(net.layers[1].weights)
print(net.get_weights())

[<tf.Variable 'dense_12/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[-0.53698206, -0.42250696,  0.18927497, -0.5560837 ],
       [ 0.8151714 ,  0.61882097,  0.3599543 , -0.5611894 ],
       [-0.69905794,  0.6539009 , -0.45241654,  0.10148877],
       [ 0.68699104, -0.5055659 ,  0.29404014, -0.44249555]],
      dtype=float32)>, <tf.Variable 'dense_12/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]
[array([[-0.53698206, -0.42250696,  0.18927497, -0.5560837 ],
       [ 0.8151714 ,  0.61882097,  0.3599543 , -0.5611894 ],
       [-0.69905794,  0.6539009 , -0.45241654,  0.10148877],
       [ 0.68699104, -0.5055659 ,  0.29404014, -0.44249555]],
      dtype=float32), array([0., 0., 0., 0.], dtype=float32), array([[ 0.16626787],
       [ 0.2467295 ],
       [-0.230353  ],
       [-0.88905907]], dtype=float32), array([0.], dtype=float32)]


In [13]:
net.get_weights()[1]

array([0., 0., 0., 0.], dtype=float32)

### 2.1.3 Collecting Parameters from Nested Blocks

In [14]:
def block1(name):
    return tf.keras.Sequential([
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(4, activation=tf.nn.relu)],
        name=name)

def block2():
    net = tf.keras.Sequential()
    for i in range(4):
        # Nested here
        net.add(block1(name=f'block-{i}'))
    return net

rgnet = tf.keras.Sequential()
rgnet.add(block2())
rgnet.add(tf.keras.layers.Dense(1))
rgnet(X)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.01037564],
       [-0.01594275]], dtype=float32)>

In [15]:
print(rgnet.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential_5 (Sequential)   (2, 4)                    80        
                                                                 
 dense_18 (Dense)            (2, 1)                    5         
                                                                 
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________
None


In [16]:
rgnet.layers[0].layers[1].layers[1].weights[1]

<tf.Variable 'dense_15/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

## 2.2 Parameters Initialization

### 2.2.1 Built-in Initialization

In [17]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4, activation=tf.nn.relu,
        kernel_initializer=tf.random_normal_initializer(mean=0, stddev=0.01),
        bias_initializer=tf.zeros_initializer()),
    tf.keras.layers.Dense(1)])

net(X)
net.weights[0], net.weights[1]

(<tf.Variable 'dense_19/kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.00321656,  0.00522881,  0.00296668, -0.00488616],
        [-0.01304954,  0.00441194, -0.009896  ,  0.00272703],
        [-0.01096619,  0.00364732, -0.01021454,  0.00996616],
        [-0.00678635,  0.00309403,  0.00794162, -0.0161864 ]],
       dtype=float32)>,
 <tf.Variable 'dense_19/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)

In [18]:
# We can also initialize all the parameters to a given constant value (say, 1).
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4, activation=tf.nn.relu,
        kernel_initializer=tf.keras.initializers.Constant(1),
        bias_initializer=tf.zeros_initializer()),
    tf.keras.layers.Dense(1),
])

net(X)
net.weights[0], net.weights[1]

(<tf.Variable 'dense_21/kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Variable 'dense_21/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)

In [19]:
# We can also apply different initializers for certain blocks. 
# For example, below we initialize the first layer with the Xavier 
# initializer and initialize the second layer to a constant value of 42.
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4,
        activation=tf.nn.relu,
        kernel_initializer=tf.keras.initializers.GlorotUniform()),
    tf.keras.layers.Dense(
        1, kernel_initializer=tf.keras.initializers.Constant(42)),
])

net(X)
print(net.layers[1].weights[0])
print(net.layers[2].weights[0])

<tf.Variable 'dense_23/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[-0.18759263, -0.36538583,  0.84754187, -0.5041744 ],
       [-0.5893924 , -0.23483795, -0.35141546,  0.56761104],
       [-0.79233265, -0.65602887, -0.45808494, -0.6857495 ],
       [ 0.22316664,  0.13502961, -0.71060264,  0.8124419 ]],
      dtype=float32)>
<tf.Variable 'dense_24/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[42.],
       [42.],
       [42.],
       [42.]], dtype=float32)>


### 2.2.2 Custom Initialization

In [20]:
class MyInit(tf.keras.initializers.Initializer):
    def __call__(self, shape, dtype=None):
        data=tf.random.uniform(shape, -10, 10, dtype=dtype)
        factor=(tf.abs(data) >= 5)
        factor=tf.cast(factor, tf.float32)
        return data * factor

net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4,
        activation=tf.nn.relu,
        kernel_initializer=MyInit()),
    tf.keras.layers.Dense(1),
])

net(X)
print(net.layers[1].weights[0])

<tf.Variable 'dense_25/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[-0.       , -0.       ,  0.       , -7.828107 ],
       [-5.730922 , -7.019737 ,  6.568758 ,  6.317213 ],
       [-8.926041 ,  7.44343  , -0.       ,  6.2375717],
       [-0.       , -9.301245 , -9.769154 , -8.604827 ]], dtype=float32)>


In [21]:
net.layers[1].weights[0][:].assign(net.layers[1].weights[0] + 1)
net.layers[1].weights[0][0, 0].assign(42)
net.layers[1].weights[0]

<tf.Variable 'dense_25/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[42.       ,  1.       ,  1.       , -6.828107 ],
       [-4.730922 , -6.019737 ,  7.568758 ,  7.317213 ],
       [-7.9260406,  8.44343  ,  1.       ,  7.2375717],
       [ 1.       , -8.301245 , -8.769154 , -7.604827 ]], dtype=float32)>

## 2.3 Tied parameters

In [22]:
# tf.keras behaves a bit differently. It removes the duplicate layer
# automatically
shared = tf.keras.layers.Dense(4, activation=tf.nn.relu)
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    shared,
    shared,
    tf.keras.layers.Dense(1),
])

net(X)
# Check whether the parameters are different
print(len(net.layers) == 3)

True


# 3. Deffered Initialization

## 3.1 Instantiating a Network

In [23]:
import tensorflow as tf

net = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dense(10),
])

In [24]:
[net.layers[i].get_weights() for i in range(len(net.layers))]

[[], []]

In [25]:
X = tf.random.uniform((2, 20))
net(X)
[w.shape for w in net.get_weights()]

[(20, 256), (256,), (256, 10), (10,)]

# 4. Custom Layers

## 4.1 Layers without Parameters

In [26]:
import tensorflow as tf


class CenteredLayer(tf.keras.Model):
    def __init__(self):
        super().__init__()

    def call(self, inputs):
        return inputs - tf.reduce_mean(inputs)

In [27]:
layer = CenteredLayer()
layer(tf.constant([1, 2, 3, 4, 5]))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-2, -1,  0,  1,  2], dtype=int32)>

In [28]:
# We can now incorporate our layer as a component in constructing more complex models.
net = tf.keras.Sequential([tf.keras.layers.Dense(128), CenteredLayer()])

In [29]:
Y = net(tf.random.uniform((4, 8)))
tf.reduce_mean(Y)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.8626451e-09>

## 4.2 Layers with Parameters

In [30]:
class MyDense(tf.keras.Model):
    def __init__(self, units):
        super().__init__()
        self.units = units

    def build(self, X_shape):
        self.weight = self.add_weight(name='weight',
            shape=[X_shape[-1], self.units],
            initializer=tf.random_normal_initializer())
        self.bias = self.add_weight(
            name='bias', shape=[self.units],
            initializer=tf.zeros_initializer())

    def call(self, X):
        linear = tf.matmul(X, self.weight) + self.bias
        return tf.nn.relu(linear)

In [31]:
# Next, we instantiate the MyDense class and access its model parameters.
dense = MyDense(3)
dense(tf.random.uniform((2, 5)))
dense.get_weights()

[array([[ 0.00939971, -0.08872261, -0.01530832],
        [-0.03869867, -0.08737626,  0.07304317],
        [-0.01980951, -0.03215084, -0.01451126],
        [ 0.02407729, -0.01643955,  0.00717759],
        [-0.03159892,  0.04607425,  0.07352412]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [32]:
# We can directly carry out forward propagation calculations using custom layers.
dense(tf.random.uniform((2, 5)))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.        , 0.        , 0.05559986],
       [0.        , 0.        , 0.07803667]], dtype=float32)>

In [33]:
# net = tf.keras.models.Sequential([MyDense(8), MyDense(1)])
net = tf.keras.models.Sequential([MyDense(8), MyDense(1)])
net(tf.random.uniform((2, 64)))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.00403171],
       [0.01881127]], dtype=float32)>

# 5. File I/O

## 5.1 Loading and Saving Tensors

In [34]:
import numpy as np
import tensorflow as tf

x = tf.range(4)
np.save('x-file.npy', x)

In [35]:
# We can now read the data from the stored file back into memory.
x2 = np.load('x-file.npy', allow_pickle=True)
x2

array([0, 1, 2, 3], dtype=int32)

In [36]:
# We can store a list of tensors and read them back into memory.
y = tf.zeros(4)
np.save('xy-files.npy', [x, y])
x2, y2 = np.load('xy-files.npy', allow_pickle=True)
(x2, y2)

(array([0., 1., 2., 3.]), array([0., 0., 0., 0.]))

In [37]:
# We can even write and read a dictionary that maps from strings to tensors. 
# This is convenient when we want to read or write all the weights in a model.
mydict = {'x': x, 'y': y}
np.save('mydict.npy', mydict)
mydict2 = np.load('mydict.npy', allow_pickle=True)
mydict2

array({'x': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>, 'y': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>},
      dtype=object)

## 5.2 Loading and Saving Model Parameters

In [38]:
class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()
        self.hidden = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
        self.out = tf.keras.layers.Dense(units=10)

    def call(self, inputs):
        x = self.flatten(inputs)
        x = self.hidden(x)
        return self.out(x)

net = MLP()
X = tf.random.uniform((2, 20))
Y = net(X)

In [39]:
# Next, we store the parameters of the model as a file with the name “mlp.params”.
net.save_weights('mlp.params')

In [40]:
# To recover the model, we instantiate a clone of the original MLP model. 
# Instead of randomly initializing the model parameters, we read the parameters stored in the file directly.
clone = MLP()
clone.load_weights('mlp.params')

In [41]:
# Since both instances have the same model parameters, the computational
# result of the same input X should be the same. Let us verify this.
Y_clone = clone(X)
Y_clone == Y

<tf.Tensor: shape=(2, 10), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])>

# 6. GPUs

In [42]:
!nvidia-smi

Tue Apr 12 15:28:35 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    57W / 149W |    195MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 6.1 Computing Devices

In [43]:
import tensorflow as tf

tf.device('/CPU:0'), tf.device('/GPU:0'), tf.device('/GPU:1')

(<tensorflow.python.eager.context._EagerDeviceContext at 0x7f7ce00d3dc0>,
 <tensorflow.python.eager.context._EagerDeviceContext at 0x7f7ce00d12d0>)

In [44]:
# We can query the number of available GPUs.
len(tf.config.experimental.list_physical_devices('GPU'))

1

In [45]:
def try_gpu(i=0):
    """Return gpu(i) if exists, otherwise return cpu()."""
    if len(tf.config.experimental.list_physical_devices('GPU')) >= i + 1:
        return tf.device(f'/GPU:{i}')
    return tf.device('/CPU:0')

def try_all_gpus():
    """Return all available GPUs, or [cpu(),] if no GPU exists."""
    num_gpus = len(tf.config.experimental.list_physical_devices('GPU'))
    devices = [tf.device(f'/GPU:{i}') for i in range(num_gpus)]
    return devices if devices else [tf.device('/CPU:0')]

try_gpu(), try_gpu(10), try_all_gpus()

(<tensorflow.python.eager.context._EagerDeviceContext at 0x7f7ce00c8550>,
 [<tensorflow.python.eager.context._EagerDeviceContext at 0x7f7ce00c8b90>])

## 6.2 Tensors and GPUs

In [46]:
x = tf.constant([1, 2, 3])
x.device

'/job:localhost/replica:0/task:0/device:GPU:0'

### 6.2.1 Storage on the GPU

In [47]:
with try_gpu():
    X = tf.ones((2, 3))
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [48]:
# Assuming that you have at least two GPUs, the following code will create a random tensor on the second GPU.
with try_gpu(1):
    Y = tf.random.uniform((2, 3))
Y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.22166204, 0.29817438, 0.39078116],
       [0.79865026, 0.8618169 , 0.7450571 ]], dtype=float32)>

### 6.2.2 Copying

In [49]:
with try_gpu(1):
    Z = X
print(X)
print(Z)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [50]:
# Now that the data are on the same GPU (both Z and Y are), we can add them up.
Y + Z

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.221662 , 1.2981744, 1.3907812],
       [1.7986503, 1.8618169, 1.7450571]], dtype=float32)>

In [51]:
with try_gpu(1):
    Z2 = Z
Z2 is Z

True

## 6.3 Neural Networks and GPUs

In [52]:
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    net = tf.keras.models.Sequential([
        tf.keras.layers.Dense(1)])

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)


In [53]:
net(X)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.9919541],
       [1.9919541]], dtype=float32)>

In [54]:
net.layers[0].weights[0].device, net.layers[0].weights[1].device

('/job:localhost/replica:0/task:0/device:GPU:0',
 '/job:localhost/replica:0/task:0/device:GPU:0')